### ISSUE TITLE
PM2 can't start service after I use nuxt-memwatch

### ISSUE THREAD

**Issue by shangxinbo** [pimlie/nuxt-memwatch#1]
When I installed nuxt-memwatch and started the service with PM2, PM2 could no longer start the application. It was inexplicable. I saw other people in the forum using memwatch-next. I noticed a hint in the document.

```
Please note you dont need to re-build your project when en-/disabling this module, you only need to restart the server
```

What is the meaning of this sentence, why not use it again, because I suspect that my problem is related to this.

**Comment by pimlie** [comment]
`nuxt-memwatch` doesnt export a plugin or anything else which need to be build with `nuxt build`. And default `nuxt-memwatch` starts working once Nuxt is listening for requests. As this is completely outside of the build phase, you can just add `nuxt-memwatch` as module to your `nuxt.config.js` and call `nuxt start` (_if_ your project was already build once ofc)

**Comment by shangxinbo** [comment]
Got It
